---
abstract: 'transform XML and XHTML to RDF'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: XML::GRDDL
name: XML-GRDDL
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
recommends:
  XML::Saxon::XSLT2: 0.003
requires:
  CSS: 0
  CSS::Parse::PRDGrammar: 0
  Data::UUID: 0
  RDF::RDFa::Parser: 1.097
  RDF::Trine: 0.135
  URI: 1.30
  URI::Escape: 0
  XML::LibXML: 1.60
  XML::LibXSLT: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=XML-GRDDL
  homepage: https://metacpan.org/release/XML-GRDDL
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-xml-grddl
version: 0.004
