---
abstract: 'transform XML and XHTML to RDF'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-GRDDL
no_index:
  directory:
    - inc
    - t
recommends:
  XML::Saxon::XSLT2: 0.003
requires:
  CSS: 0
  CSS::Parse::PRDGrammar: 0
  Carp: 1.00
  Data::UUID: 0
  Exporter: 0
  RDF::RDFa::Parser: 1.094
  RDF::Trine: 0.124
  Scalar::Util: 0
  URI: 1.30
  URI::Escape: 0
  XML::LibXML: 1.60
  XML::LibXSLT: 0
  common::sense: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=XML-GRDDL
  homepage: http://search.cpan.org/dist/XML-GRDDL/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/XML-GRDDL/
version: 0.003
